project:
  type: book
  output-dir: _site

book:
  title: "Modern Statistics for Modern Biology"
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd
    - 00-chap.qmd
    - 01-chap.qmd
    - 02-chap.qmd
    - 03-chap.qmd
    - 04-chap.qmd
    - 05-chap.qmd
    - 06-chap.qmd
    - 07-chap.qmd
    - 08-chap.qmd
    - 09-chap.qmd
    - 10-chap.qmd
    - 11-chap.qmd
    - 12-chap.qmd
    - 13-chap.qmd
    - 14-chap.qmd
    - 15-chap.qmd
    - 16-chap.qmd

format:
  html:
    theme: flatly
    css: msmb.css
    toc: true
